x-common-variables: &common-variables
  DB_USER_NAME: user1
  DB_DATABASE_NAME: task2

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  pgdata:
  audio:

services:
  db:
    image: postgres:15.3-alpine
    environment:
      <<: *common-variables
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - pgdata:/var/lib/postgresql/data

  web:
    build: ./web
    depends_on:
      - db
    environment: *common-variables
    secrets:
       - db_password
    volumes:
      - audio:/app/audio_files
    ports:
      - "8000:8000"

  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
